### ISSUE TITLE
Improve method of fetching files

### ISSUE THREAD

**Issue by programmeruser2** [RayhanADev/ReplFiles#1]
Currently. the method of fetching files is inefficient and leaves the server vulnerable to easy DoS attacks.
A better way would be to use the Replit API.
It seems like Kognise's npm package `repl.it-api` provides methods for fetching files.

**Comment by iop3** [comment]
agreed @programmeruser2

**Comment by rayhanadev** [comment]
@programmeruser2 @IcingHackz
I see where you come from, however I built this since it is the only available solution for the community. Kognise's package uses depreciated API (and is now defunct) and the Crosis/Protocol API is locked to Replit Developers.

Although I am curious how could you DoS the server (I'm not good at security).

If you have any solutions for performance or security let me know, or feel free to open a PR :D.

**Comment by rayhanadev** [comment]
@programmeruser2 
> A better way would be to use the Replit API

I'm not sure that the Replit API has any endpoints to fetch files (not that I believe there ever was one). It's probably something in the Crosis/Protocol API.

**Comment by programmeruser2** [comment]
> Although I am curious how could you DoS the server (I'm not good at security).

It should be possible to DoS by flooding the server with requests, which overloads it and leads to delays in processing time.

**Comment by rayhanadev** [comment]
@programmeruser2 then use ratelimiting? I could add that relatively easily...

**Comment by BD103** [comment]
I believe this is fixed. @RayhanADev, please close if true.

**Comment by rayhanadev** [comment]
> I believe this is fixed. @RayhanADev, please close if true.

I actually let this one go stale :O. My bad.

@programmeruser2 I implemented ratelimiting on requests, any other suggestions you might have to make the API efficient or secure?

**Comment by rayhanadev** [comment]
Side Note: @BD103 I gave you an invite to the organization and write access to this repository so that you can take care of stuff as well :)

**Comment by rayhanadev** [comment]
Closing; reason: no response.
